const traduction = {
    en: {
        aboutMeTitle: "About me",
        aboutMeDescription: "After 10 years' experience in retail, I'm now starting a new career in web development.",
        aboutMeText: "My time at OpenClassRoom gave me a solid grounding in various languages, but above all in programming logic. Since then, I've been continuing my training in web technologies.",
        timeLineTitle: "My background",
        timeLineDate1: "November 2023 - April 2024",
        timeLineTitle1: "Web Integration Training",
        timeLineSubtitle1: "OpenClassRooms",
        timeLineDate2: "March 2023 - July 2023",
        timeLineTitle2: "Self-employment",
        timeLineSubtitle2: "Real estate",
        timeLineDate3: "2012 - 2022",
        timeLineTitle3: "Marketing & Purchasing",
        timeLineSubtitle3: "Retail",
        timeLineDate4: "2012",
        timeLineTitle4: "Management degree",
        timeLineSubtitle4: "Business School",
    },
    fr: {
        aboutMeTitle: "A propos",
        aboutMeDescription: "Après 10 ans d'expérience dans le secteur de la grande distribution, j’entame aujourd’hui une nouvelle carrière en développement web.",
        aboutMeText: " Mon parcours chez OpenClassRoom m’a permis d’acquérir de solides bases dans différents langages, mais surtout en logique de programmation. Je me forme en continue sur les technologies web depuis.",
        timeLineTitle: "Mon parcours",
        timeLineDate1: "Novembre 2023 - Avril 2024",
        timeLineTitle1: "Formation Intégrateur Web",
        timeLineSubtitle1: "OpenClassRooms",
        timeLineDate2: "Mars 2023 - Juillet 2023",
        timeLineTitle2: "Auto-entrepreneur",
        timeLineSubtitle2: "Immobilier",
        timeLineDate3: "2012 - 2022",
        timeLineTitle3: "Marketing et achats",
        timeLineSubtitle3: "Grande distribution",
        timeLineDate4: "2012",
        timeLineTitle4: "Diplôme en management",
        timeLineSubtitle4: "Ecole de commerce",
    }
}

export default traduction;